#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

#Check Root
[ $(id -u) != "0" ] && { echo "Error: You must be root to run this script"; exit 1; }

echo ""
echo -e "\033[36m"
echo -e "欢迎使用 V2ray.fun 管理程序"
echo -e "\033[0m"
echo -e "1.服务管理\t\t 2.用户管理\n"
echo -e "3.更改配置\t\t 4.查看配置\n"
echo -e "5.其他设置\t\t 6.更新V2Ray\n"
echo -e "7.生成客户端配置文件"

while :; do echo
	read -n1 -p "请输入数字选择功能(按回车键退出): " choice
	if [[ ! $choice =~ ^[1-7]$ ]]; then
        if [[ -z ${choice} ]];then
            exit 0
        fi
		echo "输入错误! 请输入正确的数字!"
	else
        echo -e "\n"
		break	
	fi
done

if [[ ${choice} == 1 ]]; then
    echo -e "1.启动服务"
    echo -e "2.停止服务"
    echo -e "3.重启服务"
    echo -e "4.运行状态"
    echo -e "5.运行日志"
    while :; do echo
	    read -n1 -p "请选择： " schoice
	    if [[ ! $schoice =~ ^[1-5]$ ]]; then
            if [[ -z ${schoice} ]];then
                bash /usr/local/bin/v2ray
                exit 0
            fi
		    echo "输入错误! 请输入正确的数字!"
	    else
            echo -e "\n"
		    break
	    fi
    done
    if [[ ${schoice} == 1 ]]; then
        service v2ray start
        python3 /usr/local/v2ray.fun/base_util/open_port.py
        echo "服务启动成功！"
        bash /usr/local/bin/v2ray
    fi
    if [[ ${schoice} == 2 ]]; then
        service v2ray stop
        echo "服务停止成功！"
        bash /usr/local/bin/v2ray
    fi
    if [[ ${schoice} == 3 ]]; then
        service v2ray restart
        python3 /usr/local/v2ray.fun/base_util/open_port.py
        echo "服务已重启！"
        bash /usr/local/bin/v2ray
    fi
    if [[ ${schoice} == 4 ]]; then
        service v2ray status
        bash /usr/local/bin/v2ray
    fi
    if [[ ${schoice} == 5 ]]; then
        echo "按Ctrl + C 可以退出日志功能"
        echo ""
        tail -f /var/log/v2ray/access.log
        bash /usr/local/bin/v2ray
    fi
fi

if [[ ${choice} == 2 ]]; then
    echo -e "1.新增用户\n"
    echo -e "2.新增端口\n"
    echo -e "3.删除用户\n"
    echo -e "4.删除端口\n"
    while :; do echo
	    read -n1 -p "请输入数字选择功能： " userChoice
	    if [[ ! $userChoice =~ ^[1-4]$ ]]; then
            if [[ -z ${userChoice} ]];then
                bash /usr/local/bin/v2ray
                exit 0
            fi
		    echo "输入错误! 请输入正确的数字!"
	    else
            echo -e "\n"
		    break
	    fi
    done

    if [[ ${userChoice} == 1 ]]; then
        python3 /usr/local/v2ray.fun/user_manage/create_new_user.py
        service v2ray restart
        echo ""
        bash /usr/local/bin/v2ray
    fi
    if [[ ${userChoice} == 2 ]]; then
        python3 /usr/local/v2ray.fun/user_manage/create_new_port.py
        python3 /usr/local/v2ray.fun/base_util/open_port.py
        service v2ray restart
        echo ""
        bash /usr/local/bin/v2ray
    fi
    if [[ ${userChoice} == 3 ]]; then
        python3 /usr/local/v2ray.fun/user_manage/del_user.py
        service v2ray restart
        echo ""
        bash /usr/local/bin/v2ray
    fi
    if [[ ${userChoice} == 4 ]]; then
        python3 /usr/local/v2ray.fun/user_manage/del_port.py
        service v2ray restart
        echo ""
        bash /usr/local/bin/v2ray
    fi
fi

if [[ ${choice} == 3 ]]; then
    echo ""
    echo -e "1.更改email\n"
    echo -e "2.更改UUID\n"
    echo -e "3.更改alterID\n"
    echo -e "4.更改主端口\n"
    echo -e "5.更改传输方式\n"
    echo -e "6.更改TLS设置\n"
    echo -e "7.更改广告拦截功能\n"
    echo -e "8.更改动态端口\n"
    echo -e "请输入数字选择功能：\n"

    while :; do echo
	    read -n1 -p "请选择： " changeChoice
	    if [[ ! $changeChoice =~ ^[1-8]$ ]]; then
            if [[ -z ${changeChoice} ]];then
                bash /usr/local/bin/v2ray
                exit 0
            fi
		    echo "输入错误! 请输入正确的数字!"
	    else
            echo -e "\n"
		    break
	    fi
    done
    
    if [[ ${changeChoice} == 1 ]]; then
        python3 /usr/local/v2ray.fun/config_modify/email.py
	    service v2ray restart
        echo ""
        bash /usr/local/bin/v2ray
    fi

    if [[ ${changeChoice} == 2 ]]; then
        python3 /usr/local/v2ray.fun/config_modify/n_uuid.py
	    service v2ray restart
        echo ""
        bash /usr/local/bin/v2ray
    fi

    if [[ ${changeChoice} == 3 ]]; then
        python3 /usr/local/v2ray.fun/config_modify/alterid.py
        service v2ray restart
        echo ""
        bash /usr/local/bin/v2ray
    fi
    
    if [[ ${changeChoice} == 4 ]]; then
        python3 /usr/local/v2ray.fun/config_modify/port.py
        python3 /usr/local/v2ray.fun/base_util/open_port.py
	    service v2ray restart
        echo ""
        bash /usr/local/bin/v2ray
    fi
    
    if [[ ${changeChoice} == 5 ]]; then
        python3 /usr/local/v2ray.fun/config_modify/stream.py
	    service v2ray restart
        echo ""
        bash /usr/local/bin/v2ray
    fi
    
    if [[ ${changeChoice} == 6 ]]; then
        python3 /usr/local/v2ray.fun/config_modify/tls.py
	    service v2ray restart
        echo ""
        bash /usr/local/bin/v2ray
    fi

    if [[ ${changeChoice} == 7 ]]; then
        python3 /usr/local/v2ray.fun/config_modify/ad.py
	    service v2ray restart
        echo ""
        echo "广告拦截功能设置成功！"
        bash /usr/local/bin/v2ray
    fi

    if [[ ${changeChoice} == 8 ]]; then
        python3 /usr/local/v2ray.fun/config_modify/dyn_port.py
	    service v2ray restart
        echo ""
        bash /usr/local/bin/v2ray
    fi
fi

if [[ ${choice} == 4 ]]; then
    python3 /usr/local/v2ray.fun/server_info.py
    bash /usr/local/bin/v2ray
fi

if [[ ${choice} == 5 ]]; then
    echo -e ""
    echo -e "1.流量统计\n"
    echo -e "2.定时更新V2ray\n"
    echo -e "请输入数字选择功能：\n"

    while :; do echo
	    read -n1 -p "请选择： " extraChoice
	    if [[ ! $extraChoice =~ ^[1-2]$ ]]; then
            if [[ -z ${extraChoice} ]];then
                bash /usr/local/bin/v2ray
                exit 0
            fi
		    echo "输入错误! 请输入正确的数字!"
	    else
            echo -e "\n"
		    break
	    fi
    done

    if [[ ${extraChoice} == 1 ]]; then
        python3 /usr/local/v2ray.fun/other_setting/stats_ctr.py
        bash /usr/local/bin/v2ray
    fi

    if [[ ${extraChoice} == 2 ]]; then
        bash /usr/local/v2ray.fun/other_setting/update_timer.sh
        bash /usr/local/bin/v2ray
    fi
fi

if [[ ${choice} == 6 ]]; then
    bash <(curl -L -s https://install.direct/go.sh)
    bash /usr/local/bin/v2ray
fi

if [[ ${choice} == 7 ]]; then
    python3 /usr/local/v2ray.fun/base_util/gen_client.py
    echo -e "保存成功！(/root/config.json)\n"
    bash /usr/local/bin/v2ray
fi
